### ISSUE TITLE
Error when stopping server

### ISSUE THREAD

**Issue by TheDGOfficial** [LifeMC/LifeSkript#17]
**Describe the bug**
If you **instantly** stop the server after it opens, the Skript will give this error.

```
[15:28:53 WARN]: Exception in thread "Craft Scheduler Thread - 0" 
[15:28:53 WARN]: org.apache.commons.lang.UnhandledException: Plugin Skript v2.2-Fixes-V11 generated an exception while executing task 4
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:398)
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:123)
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:106)
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.runTask(CraftScheduler.java:89)
    at ch.njol.skript.Skript$4.run(Skript.java:545)
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more
```

**To Reproduce**
1. Create a clean server.
2. Put Skript.jar to plugins directory.
3. Start the server and send the "stop" command.

**Expected behavior**
Expected no errors, just a clean boot.

**Screenshots**
N/A

**Version information:**
 - Minecraft Version: 1.8.8 (Error occurs in all versions)
 - Skript Version: 2.2-Fixes-V11

**Additional information**
N/A

**Comment by TheDGOfficial** [comment]
Fixed with https://github.com/LifeMC/LifeSkript/commit/4e3b7680638dce50e7809357af0625007ff2872f
