### ISSUE TITLE
Minecraft 1.8 compatibility issue

### ISSUE THREAD

**Issue by TheDGOfficial** [LifeMC/LifeSkript#4]
**Describe the bug**
Current version, the V10, gives some errors on the console when enabling in Minecraft 1.8.

**To Reproduce**
Enable a 1.8.8-R0.1 server with V10 version of LifeSkript.

**Expected behavior**
Expected no errors 👍

**Screenshots**
N/A

**Version information:**
 - Minecraft Version: 1.8.8
 - Skript Version: 2.2-Fixes-V10

**Additional information**
```batch
[22:24:24] [Server thread/INFO]: [Skript] Enabling Skript v2.2-Fixes-V10
[22:24:24] [Server thread/INFO]: [Skript] Successfully generated the config, the example scripts and the aliases files.
**[22:24:27] [Server thread/ERROR]: [Skript] '?' is not an entry (like 'name : value') (config.sk, line 1: ?#     __________________________________________________________')**
[22:24:29] [Server thread/INFO]: [Skript] Loaded a total of 12584 english aliases
[22:24:29] [Server thread/INFO]: [Skript]  ~ created by & © Peter Güttinger aka Njol ~
```
```batch
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! 
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! [Skript] Severe Error:
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! Exception in thread Skript offline player resolver thread (fetches UUIDs from the minecraft servers)
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! 
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! If you're a server admin however please go to https://github.com/LifeMC/LifeSkript/issues/
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! and check whether this error has already been reported.
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! 
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! Stack trace:
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! java.lang.NullPointerException
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#!     at ch.njol.skript.bukkitutil.UnresolvedOfflinePlayer$1.run(UnresolvedOfflinePlayer.java:59)
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! 
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! Version Information:
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#!   Skript: 2.2-Fixes-V10
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#!   Minecraft: 1.8.8
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#!   Java: 1.8.0_181 (Java HotSpot(TM) 64-Bit Server VM 25.181-b13)
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! 
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! Running CraftBukkit: false
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! 
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! Current node: databases: (config.sk, line 172)
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! Current item: null
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! 
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! Thread: Skript offline player resolver thread (fetches UUIDs from the minecraft servers)
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! 
[22:24:57] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! End of Error.
[22:24:58] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! 
```

**Comment by TheDGOfficial** [comment]
This actually server version independent, but I'm not changing the title. C:
