### ISSUE TITLE
Error with property expression

### ISSUE THREAD

**Issue by TheDGOfficial** [LifeMC/LifeSkript#43]
**Describe the bug**
This error occurs when trying to get system property from an empty key

**To Reproduce**
1. Start server with Skript v2.2.14.
2. Write this to console: !property ""

**Expected behavior**
Expected no errors

**Screenshots**
N/A

**Version information:**
 - Minecraft Version: 1.8.8
 - Skript Version: 2.2.14

**Additional information**
```!property ""
[13:41:46 WARN]: Parse log wasn't instructed to print anything at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:838)
[13:41:46 WARN]: Parse log wasn't instructed to print anything at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:1030)
[13:41:46 WARN]: Parse log wasn't instructed to print anything at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1242)
[13:41:46 WARN]: Parse log wasn't instructed to print anything at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1284)
[13:41:46 WARN]: Parse log wasn't instructed to print anything at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:743)
[13:41:46 WARN]: Parse log wasn't instructed to print anything at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:161)
[13:41:46 WARN]: Retaining log wasn't instructed to print anything at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:369)
[13:41:46 ERROR]: #!#!
[13:41:46 ERROR]: #!#! [Skript] Severe Error:
[13:41:46 ERROR]: #!#! Unexpected error while executing effect command 'property ""' by 'CONSOLE'
[13:41:46 ERROR]: #!#!
[13:41:46 ERROR]: #!#! Something went horribly wrong with Skript.
[13:41:46 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[13:41:46 ERROR]: #!#!
[13:41:46 ERROR]: #!#! If you're a server admin please go to https://github.com/LifeMC/LifeSkript/issues
[13:41:46 ERROR]: #!#! and check this issue has already been reported.
[13:41:46 ERROR]: #!#!
[13:41:46 ERROR]: #!#! If not please create a new issue with a meaningful title, copy & paste this whole error into it,
[13:41:46 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[13:41:46 ERROR]: #!#!
[13:41:46 ERROR]: #!#! If you think that it's a code that's causing the error please post the code as well.
[13:41:46 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[13:41:46 ERROR]: #!#!
[13:41:46 ERROR]: #!#! Also removing the -ea java argument, lowering the verbosity or removing the problematic addons may help.
[13:41:46 ERROR]: #!#!
[13:41:46 ERROR]: #!#! Stack trace:
[13:41:46 ERROR]: #!#! java.lang.IllegalArgumentException
[13:41:46 ERROR]: #!#!     at java.lang.System.getProperty(System.java:446)
[13:41:46 ERROR]: #!#!     at java.lang.System.getProperty(System.java:433)
[13:41:46 ERROR]: #!#!     at ch.njol.skript.expressions.ExprProperty.get(ExprProperty.java:93)
[13:41:46 ERROR]: #!#!     at ch.njol.skript.expressions.ExprProperty.toString(ExprProperty.java:83)
[13:41:46 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:240)
[13:41:46 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:95)
[13:41:46 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:785)
[13:41:46 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:874)
[13:41:46 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1314)
[13:41:46 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1235)
[13:41:46 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1267)
[13:41:46 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:702)
[13:41:46 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:153)
[13:41:46 ERROR]: #!#!     at ch.njol.skript.lang.Effect.parse(Effect.java:64)
[13:41:46 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:342)
[13:41:46 ERROR]: #!#!     at ch.njol.skript.command.Commands.onServerCommand(Commands.java:237)
[13:41:46 ERROR]: #!#!     at ch.njol.skript.command.Commands.lambda$4(Commands.java:624)
[13:41:46 ERROR]: #!#!     at ch.njol.skript.command.Commands$$Lambda$64.000000001239F200.execute(Unknown Source)
[13:41:46 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[13:41:46 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:41:46 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
[13:41:46 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
[13:41:46 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:411)
[13:41:46 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379)
[13:41:46 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715)
[13:41:46 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618)
[13:41:46 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:813)
[13:41:46 ERROR]: #!#!
[13:41:46 ERROR]: #!#! Version Information:
[13:41:46 ERROR]: #!#!   Skript: 2.2.14 (latest)
[13:41:46 ERROR]: #!#!   Bukkit: 1.8.8-R0.2-SNAPSHOT (git-TacoSpigot-"95870a93" (MC: 1.8.8))
[13:41:46 ERROR]: #!#!   Minecraft: 1.8.8
[13:41:46 ERROR]: #!#!   Java: 1.8.0_212 (Eclipse OpenJ9 VM openj9-0.14.0)
[13:41:46 ERROR]: #!#!   OS: Windows 10 amd64 10.0 (64-bit)
[13:41:46 ERROR]: #!#!
[13:41:46 ERROR]: #!#! Server platform: Taco
[13:41:46 ERROR]: #!#!
[13:41:46 ERROR]: #!#! Current item: not available
[13:41:46 ERROR]: #!#! Current trigger: no trigger
[13:41:46 ERROR]: #!#!
[13:41:46 ERROR]: #!#! Thread: Server thread
[13:41:46 ERROR]: #!#!
[13:41:46 ERROR]: #!#! Language: English (system: en-US)
[13:41:46 ERROR]: #!#! Encoding: file = UTF-8 , jnu = UTF-8 , stderr = UTF-8 , stdout = UTF-8
[13:41:46 ERROR]: #!#!
[13:41:46 ERROR]: #!#!
[13:41:46 ERROR]: #!#! End of Error.
[13:41:46 ERROR]: #!#!
[13:41:46 INFO]: An internal error occurred while executing this effect. Please refer to the server log for details.```

**Comment by TheDGOfficial** [comment]
I really need to forgot adding resolves to commit message, manually closing now. :/
