### ISSUE TITLE
Another critical error that should be fixed

### ISSUE THREAD

**Issue by TheDGOfficial** [LifeMC/LifeSkript#54]
**Describe the bug**
Since Skript enables the timings by default now, it gives errors.

```
[15:02:46] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to Skript v2.2.16-beta2
java.lang.NoSuchMethodError: co.aikar.timings.Timing.startTimingIfSync()Lco/aikar/timings/Timing;
	at ch.njol.skript.timings.SkriptTimings.start(SkriptTimings.kt:42) ~[?:?]
	at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:161) ~[?:?]
	at ch.njol.skript.SkriptEventHandler.lambda$0(SkriptEventHandler.java:69) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [server-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [server-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:277) [server-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.World.addEntity(World.java:1019) [server-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:189) [Citizens.jar:?]
	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:132) [Citizens.jar:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) [Citizens.jar:?]
	at net.citizensnpcs.Citizens$2.run(Citizens.java:297) [Citizens.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [server-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [server-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [server-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [server-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [server-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [server-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
```

**To Reproduce**
Not sure.

**Expected behavior**
Expected no errors.

**Screenshots**
N/A

**Version information:**
 - Minecraft Version: 1.8.8
 - Skript Version: 2.2.16-beta2 (development build)

**Additional information**
N/A

**Comment by TheDGOfficial** [comment]
I'm fixing this now, but it's strange. We use Timings v2 API for 1.8.8, but it seems corrupted, or i use the wrong revision. Anyways, i will fix this.
