### ISSUE TITLE
Error in Minecraft 1.7

### ISSUE THREAD

**Issue by TheDGOfficial** [LifeMC/LifeSkript#7]
**Describe the bug**
Skript gives a **NoSuchMethodError** for a method in Minecraft 1.7 (or lower, i think).

**To Reproduce**
Possibly happens when looping entities in a range.

**Expected behavior**
Expected no errors at all.

**Screenshots**
N/A

**Version information:**
 - Minecraft Version: 1.7.10
 - Skript Version: 2.2-Fixes-V10c

**Additional information**
```
[20:29:52] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Skript v2.2-Fixes-V10c
java.lang.NoSuchMethodError: org.bukkit.World.getNearbyEntities(Lorg/bukkit/Location;DDD)Ljava/util/Collection;
	at ch.njol.skript.expressions.ExprEntities.iterator(ExprEntities.java:194) ~[Skript.jar:?]
	at ch.njol.skript.lang.Loop.walk(Loop.java:81) ~[Skript.jar:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91) ~[Skript.jar:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:58) ~[Skript.jar:?]
	at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:149) ~[Skript.jar:?]
	at ch.njol.skript.SkriptEventHandler$2.execute(SkriptEventHandler.java:110) ~[Skript.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:51) ~[LifeSpigot.jar:git-LifeSpigot-bf3d5f0]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[LifeSpigot.jar:git-LifeSpigot-bf3d5f0]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [LifeSpigot.jar:git-LifeSpigot-bf3d5f0]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [LifeSpigot.jar:git-LifeSpigot-bf3d5f0]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:243) [LifeSpigot.jar:git-LifeSpigot-bf3d5f0]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:213) [LifeSpigot.jar:git-LifeSpigot-bf3d5f0]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:717) [LifeSpigot.jar:git-LifeSpigot-bf3d5f0]
	at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:50) [LifeSpigot.jar:git-LifeSpigot-bf3d5f0]
	at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.handle(PacketPlayInBlockPlace.java:86) [LifeSpigot.jar:git-LifeSpigot-bf3d5f0]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:204) [LifeSpigot.jar:git-LifeSpigot-bf3d5f0]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [LifeSpigot.jar:git-LifeSpigot-bf3d5f0]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:915) [LifeSpigot.jar:git-LifeSpigot-bf3d5f0]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:313) [LifeSpigot.jar:git-LifeSpigot-bf3d5f0]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:655) [LifeSpigot.jar:git-LifeSpigot-bf3d5f0]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:556) [LifeSpigot.jar:git-LifeSpigot-bf3d5f0]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [LifeSpigot.jar:git-LifeSpigot-bf3d5f0]
```

**Comment by TheDGOfficial** [comment]
See also: afa2efd
